# Generated by Django 5.2.8 on 2025-12-03 23:38

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Usuario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100, verbose_name="Nombre")),
                ("apellido", models.CharField(max_length=100, verbose_name="Apellido")),
                (
                    "email",
                    models.EmailField(
                        max_length=254, unique=True, verbose_name="Email"
                    ),
                ),
                ("clave", models.CharField(max_length=255, verbose_name="Clave")),
                (
                    "foto_perfil",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Foto de perfil",
                    ),
                ),
                (
                    "dni",
                    models.CharField(max_length=20, unique=True, verbose_name="DNI"),
                ),
                ("rol", models.CharField(max_length=50, verbose_name="Rol")),
                ("estado", models.BooleanField(default=True, verbose_name="Estado")),
                (
                    "fecha_registro",
                    models.DateField(
                        auto_now_add=True, verbose_name="Fecha de registro"
                    ),
                ),
            ],
            options={
                "verbose_name": "Usuario",
                "verbose_name_plural": "Usuarios",
                "db_table": "usuario",
            },
        ),
        migrations.CreateModel(
            name="GrupoAtleta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100, verbose_name="Nombre")),
                (
                    "rango_edad_minima",
                    models.IntegerField(
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Rango edad mínima",
                    ),
                ),
                (
                    "rango_edad_maxima",
                    models.IntegerField(
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Rango edad máxima",
                    ),
                ),
                (
                    "categoria",
                    models.CharField(max_length=50, verbose_name="Categoría"),
                ),
                (
                    "fecha_creacion",
                    models.DateField(
                        auto_now_add=True, verbose_name="Fecha de creación"
                    ),
                ),
                ("estado", models.BooleanField(default=True, verbose_name="Estado")),
            ],
            options={
                "verbose_name": "Grupo de Atleta",
                "verbose_name_plural": "Grupos de Atletas",
                "db_table": "grupo_atleta",
                "ordering": ["nombre"],
            },
        ),
        migrations.CreateModel(
            name="Entrenador",
            fields=[
                (
                    "usuario_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="basketball.usuario",
                    ),
                ),
                (
                    "especialidad",
                    models.CharField(max_length=100, verbose_name="Especialidad"),
                ),
                (
                    "club_asignado",
                    models.CharField(max_length=100, verbose_name="Club asignado"),
                ),
            ],
            options={
                "verbose_name": "Entrenador",
                "verbose_name_plural": "Entrenadores",
                "db_table": "entrenador",
            },
            bases=("basketball.usuario",),
        ),
        migrations.CreateModel(
            name="EstudianteVinculacion",
            fields=[
                (
                    "usuario_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="basketball.usuario",
                    ),
                ),
                ("carrera", models.CharField(max_length=100, verbose_name="Carrera")),
                ("semestre", models.CharField(max_length=20, verbose_name="Semestre")),
            ],
            options={
                "verbose_name": "Estudiante de Vinculación",
                "verbose_name_plural": "Estudiantes de Vinculación",
                "db_table": "estudiante_vinculacion",
            },
            bases=("basketball.usuario",),
        ),
        migrations.CreateModel(
            name="Atleta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre_atleta",
                    models.CharField(max_length=100, verbose_name="Nombre"),
                ),
                (
                    "apellido_atleta",
                    models.CharField(max_length=100, verbose_name="Apellido"),
                ),
                (
                    "dni",
                    models.CharField(max_length=20, unique=True, verbose_name="DNI"),
                ),
                (
                    "fecha_nacimiento",
                    models.DateField(verbose_name="Fecha de nacimiento"),
                ),
                (
                    "edad",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                        verbose_name="Edad",
                    ),
                ),
                (
                    "sexo",
                    models.CharField(
                        choices=[("M", "Masculino"), ("F", "Femenino"), ("O", "Otro")],
                        max_length=1,
                        verbose_name="Sexo",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, null=True, verbose_name="Email"
                    ),
                ),
                (
                    "telefono",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="Teléfono"
                    ),
                ),
                (
                    "tipo_sangre",
                    models.CharField(
                        blank=True,
                        max_length=10,
                        null=True,
                        verbose_name="Tipo de sangre",
                    ),
                ),
                (
                    "datos_representante",
                    models.TextField(
                        blank=True, null=True, verbose_name="Datos del representante"
                    ),
                ),
                (
                    "telefono_representante",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        null=True,
                        verbose_name="Teléfono representante",
                    ),
                ),
                (
                    "grupos",
                    models.ManyToManyField(
                        related_name="atletas",
                        to="basketball.grupoatleta",
                        verbose_name="Grupos",
                    ),
                ),
            ],
            options={
                "verbose_name": "Atleta",
                "verbose_name_plural": "Atletas",
                "db_table": "atleta",
                "ordering": ["apellido_atleta", "nombre_atleta"],
            },
        ),
        migrations.CreateModel(
            name="Inscripcion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "fecha_inscripcion",
                    models.DateField(verbose_name="Fecha de inscripción"),
                ),
                (
                    "tipo_inscripcion",
                    models.CharField(
                        choices=[
                            ("FEDERADO", "Federado"),
                            ("NO_FEDERADO", "No Federado"),
                            ("INVITADO", "Invitado"),
                        ],
                        max_length=20,
                        verbose_name="Tipo de inscripción",
                    ),
                ),
                (
                    "fecha_creacion",
                    models.DateField(
                        auto_now_add=True, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "habilitada",
                    models.BooleanField(default=True, verbose_name="Habilitada"),
                ),
                (
                    "atleta",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inscripcion",
                        to="basketball.atleta",
                        verbose_name="Atleta",
                    ),
                ),
            ],
            options={
                "verbose_name": "Inscripción",
                "verbose_name_plural": "Inscripciones",
                "db_table": "inscripcion",
                "ordering": ["-fecha_inscripcion"],
            },
        ),
        migrations.CreateModel(
            name="PruebaAntropometrica",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha_registro", models.DateField(verbose_name="Fecha de registro")),
                (
                    "indice_masa_corporal",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                        verbose_name="Índice de masa corporal",
                    ),
                ),
                (
                    "estatura",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                        verbose_name="Estatura (cm)",
                    ),
                ),
                (
                    "altura_sentado",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                        verbose_name="Altura sentado (cm)",
                    ),
                ),
                (
                    "envergadura",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                        verbose_name="Envergadura (cm)",
                    ),
                ),
                (
                    "indice_cornico",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        verbose_name="Índice córnico",
                    ),
                ),
                (
                    "observaciones",
                    models.TextField(
                        blank=True, null=True, verbose_name="Observaciones"
                    ),
                ),
                ("estado", models.BooleanField(default=True, verbose_name="Estado")),
                (
                    "atleta",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pruebas_antropometricas",
                        to="basketball.atleta",
                        verbose_name="Atleta",
                    ),
                ),
            ],
            options={
                "verbose_name": "Prueba Antropométrica",
                "verbose_name_plural": "Pruebas Antropométricas",
                "db_table": "prueba_antropometrica",
                "ordering": ["-fecha_registro"],
            },
        ),
        migrations.CreateModel(
            name="PruebaFisica",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha_registro", models.DateField(verbose_name="Fecha de registro")),
                (
                    "tipo_prueba",
                    models.CharField(
                        choices=[
                            ("VELOCIDAD", "Velocidad"),
                            ("RESISTENCIA", "Resistencia"),
                            ("FUERZA", "Fuerza"),
                            ("FLEXIBILIDAD", "Flexibilidad"),
                            ("COORDINACION", "Coordinación"),
                            ("AGILIDAD", "Agilidad"),
                        ],
                        max_length=20,
                        verbose_name="Tipo de prueba",
                    ),
                ),
                (
                    "resultado",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Resultado"
                    ),
                ),
                (
                    "unidad_medida",
                    models.CharField(max_length=20, verbose_name="Unidad de medida"),
                ),
                (
                    "observaciones",
                    models.TextField(
                        blank=True, null=True, verbose_name="Observaciones"
                    ),
                ),
                ("estado", models.BooleanField(default=True, verbose_name="Estado")),
                (
                    "atleta",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pruebas_fisicas",
                        to="basketball.atleta",
                        verbose_name="Atleta",
                    ),
                ),
            ],
            options={
                "verbose_name": "Prueba Física",
                "verbose_name_plural": "Pruebas Físicas",
                "db_table": "prueba_fisica",
                "ordering": ["-fecha_registro"],
            },
        ),
        migrations.AddField(
            model_name="grupoatleta",
            name="entrenador",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="grupos",
                to="basketball.entrenador",
                verbose_name="Entrenador",
            ),
        ),
    ]
