# Generated by Django 4.2.7 on 2025-12-22 02:17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("basketball", "0005_estudiante_vinculacion_eliminado"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="entrenador",
            options={
                "ordering": ["persona_external"],
                "verbose_name": "Entrenador",
                "verbose_name_plural": "Entrenadores",
            },
        ),
    ]
