# Generated by Django 4.2.7 on 2025-12-23 23:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("basketball", "0006_alter_entrenador_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="atleta",
            options={
                "ordering": ["persona_external"],
                "verbose_name": "Atleta",
                "verbose_name_plural": "Atletas",
            },
        ),
        migrations.RemoveField(
            model_name="atleta",
            name="apellido_atleta",
        ),
        migrations.RemoveField(
            model_name="atleta",
            name="datos_representante",
        ),
        migrations.RemoveField(
            model_name="atleta",
            name="dni",
        ),
        migrations.RemoveField(
            model_name="atleta",
            name="email",
        ),
        migrations.RemoveField(
            model_name="atleta",
            name="nombre_atleta",
        ),
        migrations.AddField(
            model_name="atleta",
            name="dni_representante",
            field=models.CharField(
                blank=True,
                max_length=20,
                null=True,
                verbose_name="Cédula/DNI representante",
            ),
        ),
        migrations.AddField(
            model_name="atleta",
            name="email_representante",
            field=models.EmailField(
                blank=True,
                max_length=254,
                null=True,
                verbose_name="Correo electrónico representante",
            ),
        ),
        migrations.AddField(
            model_name="atleta",
            name="enfermedades_lesiones",
            field=models.TextField(
                blank=True, null=True, verbose_name="Enfermedades o lesiones crónicas"
            ),
        ),
        migrations.AddField(
            model_name="atleta",
            name="nombre_representante",
            field=models.CharField(
                blank=True,
                max_length=100,
                null=True,
                verbose_name="Nombre representante",
            ),
        ),
        migrations.AddField(
            model_name="atleta",
            name="parentesco_representante",
            field=models.CharField(
                blank=True,
                max_length=50,
                null=True,
                verbose_name="Parentesco representante",
            ),
        ),
        migrations.AddField(
            model_name="atleta",
            name="persona_external",
            field=models.CharField(
                help_text="UUID externo de la persona en el módulo de usuarios",
                max_length=100,
                null=True,
                unique=True,
                verbose_name="External ID Persona",
            ),
        ),
        migrations.AlterField(
            model_name="atleta",
            name="fecha_nacimiento",
            field=models.DateField(null=True, verbose_name="Fecha de nacimiento"),
        ),
        migrations.AlterField(
            model_name="atleta",
            name="tipo_sangre",
            field=models.CharField(
                blank=True, max_length=10, null=True, verbose_name="Tipo de sangre (RH)"
            ),
        ),
    ]
