# Generated by Django 4.2.26 on 2025-12-29 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("basketball", "0006_alter_entrenador_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="entrenador",
            name="eliminado",
            field=models.BooleanField(default=False, verbose_name="Eliminado"),
        ),
    ]
