# Generated by Django 4.2.7 on 2025-12-23 23:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "basketball",
            "0007_alter_atleta_options_remove_atleta_apellido_atleta_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="atleta",
            name="dni_representante",
        ),
        migrations.RemoveField(
            model_name="atleta",
            name="email_representante",
        ),
        migrations.RemoveField(
            model_name="atleta",
            name="enfermedades_lesiones",
        ),
        migrations.AddField(
            model_name="atleta",
            name="alergias",
            field=models.TextField(blank=True, null=True, verbose_name="Alergias"),
        ),
        migrations.AddField(
            model_name="atleta",
            name="cedula_representante",
            field=models.CharField(
                blank=True,
                max_length=20,
                null=True,
                verbose_name="Cédula representante",
            ),
        ),
        migrations.AddField(
            model_name="atleta",
            name="correo_representante",
            field=models.EmailField(
                blank=True,
                max_length=254,
                null=True,
                verbose_name="Correo representante",
            ),
        ),
        migrations.AddField(
            model_name="atleta",
            name="direccion_representante",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="Dirección representante",
            ),
        ),
        migrations.AddField(
            model_name="atleta",
            name="enfermedades",
            field=models.TextField(blank=True, null=True, verbose_name="Enfermedades"),
        ),
        migrations.AddField(
            model_name="atleta",
            name="lesiones",
            field=models.TextField(blank=True, null=True, verbose_name="Lesiones"),
        ),
        migrations.AddField(
            model_name="atleta",
            name="medicamentos",
            field=models.TextField(blank=True, null=True, verbose_name="Medicamentos"),
        ),
        migrations.AddField(
            model_name="atleta",
            name="ocupacion_representante",
            field=models.CharField(
                blank=True,
                max_length=100,
                null=True,
                verbose_name="Ocupación representante",
            ),
        ),
        migrations.AlterField(
            model_name="atleta",
            name="sexo",
            field=models.CharField(max_length=20, verbose_name="Sexo"),
        ),
    ]
