# Generated by Django 6.0 on 2025-12-22 20:14

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basketball', '0007_remove_pruebaantropometrica_indice_cornico_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pruebaantropometrica',
            name='altura_sentado',
            field=models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Altura sentado (cm)'),
        ),
        migrations.AlterField(
            model_name='pruebaantropometrica',
            name='envergadura',
            field=models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Envergadura (cm)'),
        ),
        migrations.AlterField(
            model_name='pruebaantropometrica',
            name='estatura',
            field=models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Estatura (cm)'),
        ),
    ]
