# Generated by Django 4.2.7 on 2025-12-27 00:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("basketball", "0007_entrenador_eliminado"),
    ]

    operations = [
        migrations.AddField(
            model_name="grupoatleta",
            name="entrenador",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="grupos",
                to="basketball.entrenador",
                to_field="persona_external",
                verbose_name="Entrenador",
            ),
        ),
    ]
