# Generated by Django 4.2.7 on 2025-12-29 21:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("basketball", "0008_remove_atleta_dni_representante_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="inscripcion",
            name="tipo_inscripcion",
            field=models.CharField(
                choices=[
                    ("MENOR_EDAD", "Menor de edad (con representante)"),
                    ("MAYOR_EDAD", "Mayor de edad"),
                ],
                max_length=20,
                verbose_name="Tipo de inscripción",
            ),
        ),
    ]
