# Generated by Django 6.0 on 2025-12-27 19:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("basketball", "0008_alter_pruebaantropometrica_altura_sentado_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="grupoatleta",
            name="entrenador",
        ),
        migrations.AddField(
            model_name="grupoatleta",
            name="entrenador",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="grupos",
                to="basketball.entrenador",
                verbose_name="Entrenador",
            ),
        ),
    ]
