# Generated by Django 5.2.8 on 2025-12-29 23:12

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("basketball", "0007_entrenador_eliminado"),
        ("basketball", "0009_alter_inscripcion_tipo_inscripcion"),
    ]

    operations = []
