# Generated by Django 4.2.7 on 2025-12-24 14:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("basketball", "0007_entrenador_eliminado"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pruebafisica",
            name="tipo_prueba",
            field=models.CharField(
                choices=[
                    ("FUERZA", "Fuerza"),
                    ("VELOCIDAD", "Velocidad"),
                    ("AGILIDAD", "Agilidad"),
                ],
                max_length=20,
                verbose_name="Tipo de prueba",
            ),
        ),
    ]
