# Generated by Django 5.2.8 on 2026-01-04 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basketball', '0011_alter_pruebafisica_tipo_prueba'),
    ]

    operations = [
        migrations.AddField(
            model_name='atleta',
            name='apellidos',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Apellidos'),
        ),
        migrations.AddField(
            model_name='atleta',
            name='cedula',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Cédula/Identificación'),
        ),
        migrations.AddField(
            model_name='atleta',
            name='nombres',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Nombres'),
        ),
    ]
