# Generated by Django 4.2.26 on 2025-12-31 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basketball', '0011_alter_pruebafisica_tipo_prueba'),
    ]

    operations = [
        migrations.AddField(
            model_name='grupoatleta',
            name='eliminado',
            field=models.BooleanField(default=False, verbose_name='Eliminado'),
        ),
    ]
