# Generated by Django 4.2.26 on 2025-12-31 02:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("basketball", "0012_add_local_persona_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="grupoatleta",
            name="eliminado",
            field=models.BooleanField(default=False, verbose_name="Eliminado"),
        ),
    ]
