# Generated by Django 4.2.7 on 2026-01-02 22:38

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("basketball", "0012_remove_pruebaantropometrica_indice_cornico_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="pruebaantropometrica",
            name="indice_cornico",
        ),
        migrations.AddField(
            model_name="pruebaantropometrica",
            name="indice_cormico",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                editable=False,
                max_digits=5,
                verbose_name="Índice Córmico",
            ),
        ),
    ]
