# Generated by Django 4.2.7 on 2026-01-03 21:30

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("basketball", "0011_alter_pruebafisica_tipo_prueba"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pruebafisica",
            name="resultado",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
                verbose_name="Resultado",
            ),
        ),
    ]
