# Generated by Django 4.2.7 on 2026-01-03 22:30

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("basketball", "0014_alter_pruebafisica_resultado"),
    ]

    operations = []
