# Generated by Django 4.2.7 on 2026-01-03 21:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basketball', '0013_remove_pruebaantropometrica_indice_cornico_and_more'),
        ('basketball', '0014_alter_pruebafisica_resultado'),
    ]

    operations = [
    ]
