# Generated by Django 4.2.26 on 2026-01-03 21:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basketball', '0012_grupoatleta_eliminado'),
        ('basketball', '0013_remove_pruebaantropometrica_indice_cornico_and_more'),
    ]

    operations = [
    ]
