# Generated by Django 5.2.8 on 2026-01-04 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basketball', '0013_add_email_direccion_genero'),
        ('basketball', '0015_merge_all'),
    ]

    operations = [
    ]
