# Generated by Django 4.2.7 on 2026-01-31 23:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basketball', '0017_alter_entrenador_club_asignado_and_more'),
        ('basketball', '0017_alter_pruebafisica_resultado'),
    ]

    operations = [
    ]
