# Generated by Django 5.2.8 on 2026-02-01 07:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("basketball", "0018_merge_20260131_1853"),
    ]

    operations = [
        migrations.AlterField(
            model_name="atleta",
            name="alergias",
            field=models.CharField(
                blank=True,
                help_text="Máximo 100 caracteres",
                max_length=100,
                null=True,
                verbose_name="Alergias",
            ),
        ),
        migrations.AlterField(
            model_name="atleta",
            name="direccion",
            field=models.CharField(
                blank=True,
                help_text="Máximo 75 caracteres",
                max_length=75,
                null=True,
                verbose_name="Dirección",
            ),
        ),
        migrations.AlterField(
            model_name="atleta",
            name="direccion_representante",
            field=models.CharField(
                blank=True,
                help_text="Máximo 75 caracteres",
                max_length=75,
                null=True,
                verbose_name="Dirección representante",
            ),
        ),
        migrations.AlterField(
            model_name="atleta",
            name="enfermedades",
            field=models.CharField(
                blank=True,
                help_text="Máximo 100 caracteres",
                max_length=100,
                null=True,
                verbose_name="Enfermedades",
            ),
        ),
        migrations.AlterField(
            model_name="atleta",
            name="lesiones",
            field=models.CharField(
                blank=True,
                help_text="Máximo 100 caracteres",
                max_length=100,
                null=True,
                verbose_name="Lesiones",
            ),
        ),
        migrations.AlterField(
            model_name="atleta",
            name="medicamentos",
            field=models.CharField(
                blank=True,
                help_text="Máximo 100 caracteres",
                max_length=100,
                null=True,
                verbose_name="Medicamentos",
            ),
        ),
    ]
