# Generated by Django 4.2.7 on 2026-02-01 02:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("basketball", "0018_merge_20260131_1853"),
    ]

    operations = []
